server:
  port: 8206

mybatis-plus:
  type-enums-package: com.hello.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.168.87:3306/shequ-user?characterEncoding=utf-8&useSSL=false
    username: shequ-user
    password: Kw7AZ7nJMpsr2iBW

  redis:
    host: 124.222.168.87
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

wx:
  open:
    # 小程序微信公众平台appId
    app_id: wxab7d31a2c2a69b44
    # 小程序微信公众平台api秘钥
    app_secret: 59de9f5e720c10d7c95ff10c8b56ad2f